//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompuMarket_App.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int id { get; set; }
        public string AdressOrder { get; set; }
        public long Number { get; set; }
        public int Product_id { get; set; }
        public int User_id { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Users Users { get; set; }

        public Orders() { }
        public Orders(string AdressOrder, long Number, Products Products, Users Users)
        {
            this.AdressOrder = AdressOrder;
            this.Number = Number;
            this.Products = Products;
            this.Users = Users;
        }
    }
}
