//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompuMarket_App.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workers
    {
        public int IdWorkers { get; set; }
        public string Salary { get; set; }
        public Nullable<int> TypeID { get; set; }
        public string Phone { get; set; }
        public string Adress { get; set; }
    
        public virtual TypeWork TypeWork { get; set; }
    }
}
